/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

/**
 *
 * @author cachi
 */
public class Expedientes extends javax.swing.JFrame {

    /**
     * Creates new form Expedientes
     */
    public Expedientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        ESMALTE = new javax.swing.JRadioButton();
        DENTINA = new javax.swing.JRadioButton();
        RAIZ = new javax.swing.JRadioButton();
        HUESOS = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        ENCIA = new javax.swing.JRadioButton();
        VELO = new javax.swing.JRadioButton();
        INSERCION = new javax.swing.JRadioButton();
        CARRILLOS = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        DESMAYOS = new javax.swing.JRadioButton();
        EMBARAZADA = new javax.swing.JRadioButton();
        ONOCLUSION = new javax.swing.JRadioButton();
        MAREOS = new javax.swing.JRadioButton();
        OTROS = new javax.swing.JRadioButton();
        SOBRE = new javax.swing.JRadioButton();
        DESGASTE = new javax.swing.JRadioButton();
        INTER = new javax.swing.JRadioButton();
        VERTIGOS = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        BRICOMANIA = new javax.swing.JRadioButton();
        MORDIDA = new javax.swing.JRadioButton();
        CONTRACCIONES = new javax.swing.JRadioButton();
        BUCAL = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(734, 444));
        setMinimumSize(new java.awt.Dimension(734, 444));
        setPreferredSize(new java.awt.Dimension(734, 444));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nombre:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 29, -1, -1));

        jLabel2.setText("Domicilio:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jLabel3.setText("Telefono:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jTextField1.setText("******");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 200, -1));

        jTextField2.setText("jTextField2");
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 200, -1));

        jTextField3.setText("jTextField3");
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 200, -1));

        jLabel4.setText("Ocupacion:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        jTextField4.setText("jTextField4");
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 200, -1));

        jLabel5.setText("Edad:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        jTextField5.setText("jTextField5");
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 60, -1));

        jLabel6.setText("Sexo:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Masculino", "Femenino" }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 80, -1));

        jLabel7.setText("Sintomas");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, -1, -1));

        jLabel9.setText("EXAMEN DE TEJIDOS");

        ESMALTE.setText("ESMALTE");
        ESMALTE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ESMALTEMouseClicked(evt);
            }
        });

        DENTINA.setText("DENTINA");
        DENTINA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DENTINAMouseClicked(evt);
            }
        });

        RAIZ.setText("RAIZ");
        RAIZ.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RAIZMouseClicked(evt);
            }
        });

        HUESOS.setText("HUESOS");
        HUESOS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HUESOSMouseClicked(evt);
            }
        });
        HUESOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HUESOSActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(RAIZ)
                                .addGap(28, 28, 28))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addComponent(ESMALTE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(HUESOS)
                            .addComponent(DENTINA))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ESMALTE)
                    .addComponent(DENTINA))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RAIZ)
                    .addComponent(HUESOS))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, -1, -1));

        jLabel10.setText("BLANDOS");

        ENCIA.setText("ENCIA");
        ENCIA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ENCIAMouseClicked(evt);
            }
        });

        VELO.setText("VELO DE PALADAR");
        VELO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VELOMouseClicked(evt);
            }
        });

        INSERCION.setText("INSERCION");
        INSERCION.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                INSERCIONMouseClicked(evt);
            }
        });

        CARRILLOS.setText("CARRILLOS");
        CARRILLOS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CARRILLOSMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(ENCIA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(VELO)
                        .addGap(113, 113, 113))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(CARRILLOS)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(INSERCION)
                        .addGap(155, 155, 155))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ENCIA)
                    .addComponent(VELO))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CARRILLOS)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(INSERCION)
                        .addContainerGap())))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 40, 210, -1));

        jLabel11.setText("OCLUSION");

        DESMAYOS.setText("DESMAYOS");
        DESMAYOS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DESMAYOSMouseClicked(evt);
            }
        });

        EMBARAZADA.setText("SE ENCUENTRA EMBARAZADA");
        EMBARAZADA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EMBARAZADAMouseClicked(evt);
            }
        });

        ONOCLUSION.setText("ONOCLUSION");
        ONOCLUSION.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ONOCLUSIONMouseClicked(evt);
            }
        });

        MAREOS.setText("MAREOS");
        MAREOS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MAREOSMouseClicked(evt);
            }
        });
        MAREOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MAREOSActionPerformed(evt);
            }
        });

        OTROS.setText("OTROS");
        OTROS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OTROSMouseClicked(evt);
            }
        });

        SOBRE.setText("SOBRE MORDIDA VERTICAL");
        SOBRE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SOBREMouseClicked(evt);
            }
        });

        DESGASTE.setText("DESGASTE ");
        DESGASTE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DESGASTEMouseClicked(evt);
            }
        });

        INTER.setText("INTERCUSPIDEO");
        INTER.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                INTERMouseClicked(evt);
            }
        });

        VERTIGOS.setText("VERTIGOS");
        VERTIGOS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VERTIGOSMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(213, 213, 213))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ONOCLUSION)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(MAREOS)
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(SOBRE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(DESMAYOS)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DESGASTE)
                            .addComponent(VERTIGOS))))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(INTER)
                    .addComponent(EMBARAZADA)
                    .addComponent(OTROS))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SOBRE)
                    .addComponent(DESGASTE)
                    .addComponent(INTER))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VERTIGOS)
                    .addComponent(DESMAYOS)
                    .addComponent(EMBARAZADA))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ONOCLUSION)
                    .addComponent(MAREOS)
                    .addComponent(OTROS)))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, -1, -1));

        jLabel12.setText("HABITOS");

        BRICOMANIA.setText("BRICOMANIA");
        BRICOMANIA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BRICOMANIAMouseClicked(evt);
            }
        });

        MORDIDA.setText("HABITOS DE MORDIDA");
        MORDIDA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MORDIDAMouseClicked(evt);
            }
        });

        CONTRACCIONES.setText("CONTRACCIONES MUSCULARES");
        CONTRACCIONES.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CONTRACCIONESMouseClicked(evt);
            }
        });

        BUCAL.setText("RESPIRACION BUCAL");
        BUCAL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BUCALMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(jLabel12))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MORDIDA)
                            .addComponent(BRICOMANIA))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CONTRACCIONES)
                            .addComponent(BUCAL))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BRICOMANIA)
                    .addComponent(CONTRACCIONES))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MORDIDA)
                    .addComponent(BUCAL))
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, -1, -1));

        jButton1.setText("Crear Expediente");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 210, -1));

        jButton2.setText("Nuevo Expediente");
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 210, -1));

        jButton3.setText("Cancelar");
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 210, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void ESMALTEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ESMALTEMouseClicked
        
    }//GEN-LAST:event_ESMALTEMouseClicked

    private void DENTINAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DENTINAMouseClicked
        
    }//GEN-LAST:event_DENTINAMouseClicked

    private void RAIZMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RAIZMouseClicked
        
    }//GEN-LAST:event_RAIZMouseClicked

    private void HUESOSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HUESOSMouseClicked
        
    }//GEN-LAST:event_HUESOSMouseClicked

    private void HUESOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HUESOSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HUESOSActionPerformed

    private void ENCIAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ENCIAMouseClicked
        
    }//GEN-LAST:event_ENCIAMouseClicked

    private void VELOMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VELOMouseClicked
        
    }//GEN-LAST:event_VELOMouseClicked

    private void INSERCIONMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_INSERCIONMouseClicked
        
    }//GEN-LAST:event_INSERCIONMouseClicked

    private void CARRILLOSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CARRILLOSMouseClicked
        
    }//GEN-LAST:event_CARRILLOSMouseClicked

    private void DESMAYOSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DESMAYOSMouseClicked
        
    }//GEN-LAST:event_DESMAYOSMouseClicked

    private void EMBARAZADAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EMBARAZADAMouseClicked
        
    }//GEN-LAST:event_EMBARAZADAMouseClicked

    private void ONOCLUSIONMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ONOCLUSIONMouseClicked
        
    }//GEN-LAST:event_ONOCLUSIONMouseClicked

    private void MAREOSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MAREOSMouseClicked
        
    }//GEN-LAST:event_MAREOSMouseClicked

    private void MAREOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MAREOSActionPerformed
        
    }//GEN-LAST:event_MAREOSActionPerformed

    private void OTROSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OTROSMouseClicked
        
    }//GEN-LAST:event_OTROSMouseClicked

    private void SOBREMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SOBREMouseClicked
        
    }//GEN-LAST:event_SOBREMouseClicked

    private void DESGASTEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DESGASTEMouseClicked
        
    }//GEN-LAST:event_DESGASTEMouseClicked

    private void INTERMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_INTERMouseClicked
        
    }//GEN-LAST:event_INTERMouseClicked

    private void VERTIGOSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VERTIGOSMouseClicked
        
    }//GEN-LAST:event_VERTIGOSMouseClicked

    private void BRICOMANIAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BRICOMANIAMouseClicked
       
    }//GEN-LAST:event_BRICOMANIAMouseClicked

    private void MORDIDAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MORDIDAMouseClicked
        
    }//GEN-LAST:event_MORDIDAMouseClicked

    private void CONTRACCIONESMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CONTRACCIONESMouseClicked
        
    }//GEN-LAST:event_CONTRACCIONESMouseClicked

    private void BUCALMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BUCALMouseClicked
        
    }//GEN-LAST:event_BUCALMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Expedientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Expedientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Expedientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Expedientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Expedientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton BRICOMANIA;
    private javax.swing.JRadioButton BUCAL;
    private javax.swing.JRadioButton CARRILLOS;
    private javax.swing.JRadioButton CONTRACCIONES;
    private javax.swing.JRadioButton DENTINA;
    private javax.swing.JRadioButton DESGASTE;
    private javax.swing.JRadioButton DESMAYOS;
    private javax.swing.JRadioButton EMBARAZADA;
    private javax.swing.JRadioButton ENCIA;
    private javax.swing.JRadioButton ESMALTE;
    private javax.swing.JRadioButton HUESOS;
    private javax.swing.JRadioButton INSERCION;
    private javax.swing.JRadioButton INTER;
    private javax.swing.JRadioButton MAREOS;
    private javax.swing.JRadioButton MORDIDA;
    private javax.swing.JRadioButton ONOCLUSION;
    private javax.swing.JRadioButton OTROS;
    private javax.swing.JRadioButton RAIZ;
    private javax.swing.JRadioButton SOBRE;
    private javax.swing.JRadioButton VELO;
    private javax.swing.JRadioButton VERTIGOS;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
