/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import conexionSQL.Conexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author cachi
 */
public class Expedientes extends javax.swing.JFrame {
String esmalte="",dentina="",raiz="",huesos="",encia="",velo="",carrillos="",insercion="",sobre="",desgaste="",intercuspideo="",desmayos="",vertigos="",
        embarazada="",onoclusion="";
String mareos="",otros="",bricomania="",contraccion="",mordida="",bucal="";
    /**
     * Creates new form Expedientes
     */
    public Expedientes() {
        initComponents();
        this.setResizable(false);
        //this.setExtendedState(MAXIMIZED_BOTH);
        
    }
    

      Conexion cc=new Conexion();
        Connection con=cc.conectar();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        ESMALTE = new javax.swing.JRadioButton();
        DENTINA = new javax.swing.JRadioButton();
        RAIZ = new javax.swing.JRadioButton();
        HUESOS = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        ENCIA = new javax.swing.JRadioButton();
        VELO = new javax.swing.JRadioButton();
        INSERCION = new javax.swing.JRadioButton();
        CARRILLOS = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        DESMAYOS = new javax.swing.JRadioButton();
        EMBARAZADA = new javax.swing.JRadioButton();
        ONOCLUSION = new javax.swing.JRadioButton();
        MAREOS = new javax.swing.JRadioButton();
        OTROS = new javax.swing.JRadioButton();
        SOBRE = new javax.swing.JRadioButton();
        DESGASTE = new javax.swing.JRadioButton();
        INTER = new javax.swing.JRadioButton();
        VERTIGOS = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        BRICOMANIA = new javax.swing.JRadioButton();
        MORDIDA = new javax.swing.JRadioButton();
        CONTRACCIONES = new javax.swing.JRadioButton();
        BUCAL = new javax.swing.JRadioButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setPreferredSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 102, 255));
        jLabel1.setText("Nombre:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 102, 255));
        jLabel2.setText("Domicilio:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 102, 255));
        jLabel3.setText("Telefono:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 200, -1));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 200, -1));

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField3KeyTyped(evt);
            }
        });
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 200, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 102, 255));
        jLabel4.setText("Ocupacion:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField4KeyTyped(evt);
            }
        });
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 200, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 102, 255));
        jLabel5.setText("Edad:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        jTextField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField5KeyTyped(evt);
            }
        });
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, 60, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 102, 255));
        jLabel6.setText("Sexo:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Masculino", "Femenino" }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, 80, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 102, 255));
        jLabel7.setText("Sintomas");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 120, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 102, 255));
        jLabel9.setText("EXAMEN DE TEJIDOS");

        ESMALTE.setText("ESMALTE");
        ESMALTE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ESMALTEMouseClicked(evt);
            }
        });
        ESMALTE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ESMALTEActionPerformed(evt);
            }
        });

        DENTINA.setText("DENTINA");
        DENTINA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DENTINAMouseClicked(evt);
            }
        });
        DENTINA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DENTINAActionPerformed(evt);
            }
        });

        RAIZ.setText("RAIZ");
        RAIZ.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RAIZMouseClicked(evt);
            }
        });
        RAIZ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RAIZActionPerformed(evt);
            }
        });

        HUESOS.setText("HUESOS");
        HUESOS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HUESOSMouseClicked(evt);
            }
        });
        HUESOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HUESOSActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(RAIZ)
                                .addGap(28, 28, 28))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(ESMALTE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(HUESOS)
                            .addComponent(DENTINA))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ESMALTE)
                    .addComponent(DENTINA))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RAIZ)
                    .addComponent(HUESOS))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 150, -1, 110));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 102, 255));
        jLabel10.setText("BLANDOS");

        ENCIA.setText("ENCIA");
        ENCIA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ENCIAMouseClicked(evt);
            }
        });
        ENCIA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ENCIAActionPerformed(evt);
            }
        });

        VELO.setText("VELO DE PALADAR");
        VELO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VELOMouseClicked(evt);
            }
        });
        VELO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VELOActionPerformed(evt);
            }
        });

        INSERCION.setText("INSERCION");
        INSERCION.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                INSERCIONMouseClicked(evt);
            }
        });
        INSERCION.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                INSERCIONActionPerformed(evt);
            }
        });

        CARRILLOS.setText("CARRILLOS");
        CARRILLOS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CARRILLOSMouseClicked(evt);
            }
        });
        CARRILLOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CARRILLOSActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ENCIA)
                    .addComponent(CARRILLOS, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(VELO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(INSERCION, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(113, 113, 113))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ENCIA)
                    .addComponent(VELO))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CARRILLOS)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(INSERCION)
                        .addContainerGap())))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 154, 220, 110));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 102, 255));
        jLabel11.setText("OCLUSION");

        DESMAYOS.setText("DESMAYOS");
        DESMAYOS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DESMAYOSMouseClicked(evt);
            }
        });
        DESMAYOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DESMAYOSActionPerformed(evt);
            }
        });

        EMBARAZADA.setText("SE ENCUENTRA EMBARAZADA");
        EMBARAZADA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EMBARAZADAMouseClicked(evt);
            }
        });
        EMBARAZADA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EMBARAZADAActionPerformed(evt);
            }
        });

        ONOCLUSION.setText("ONOCLUSION");
        ONOCLUSION.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ONOCLUSIONMouseClicked(evt);
            }
        });
        ONOCLUSION.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ONOCLUSIONActionPerformed(evt);
            }
        });

        MAREOS.setText("MAREOS");
        MAREOS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MAREOSMouseClicked(evt);
            }
        });
        MAREOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MAREOSActionPerformed(evt);
            }
        });

        OTROS.setText("OTROS");
        OTROS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OTROSMouseClicked(evt);
            }
        });
        OTROS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OTROSActionPerformed(evt);
            }
        });

        SOBRE.setText("SOBRE MORDIDA VERTICAL");
        SOBRE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SOBREMouseClicked(evt);
            }
        });
        SOBRE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SOBREActionPerformed(evt);
            }
        });

        DESGASTE.setText("DESGASTE ");
        DESGASTE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DESGASTEMouseClicked(evt);
            }
        });
        DESGASTE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DESGASTEActionPerformed(evt);
            }
        });

        INTER.setText("INTERCUSPIDEO");
        INTER.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                INTERMouseClicked(evt);
            }
        });
        INTER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                INTERActionPerformed(evt);
            }
        });

        VERTIGOS.setText("VERTIGOS");
        VERTIGOS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VERTIGOSMouseClicked(evt);
            }
        });
        VERTIGOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VERTIGOSActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(213, 213, 213))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ONOCLUSION)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(MAREOS)
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(SOBRE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(DESMAYOS)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DESGASTE)
                            .addComponent(VERTIGOS))))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(INTER)
                    .addComponent(EMBARAZADA)
                    .addComponent(OTROS))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SOBRE)
                    .addComponent(DESGASTE)
                    .addComponent(INTER))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VERTIGOS)
                    .addComponent(DESMAYOS)
                    .addComponent(EMBARAZADA))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ONOCLUSION)
                    .addComponent(MAREOS)
                    .addComponent(OTROS)))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 270, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 102, 255));
        jLabel12.setText("HABITOS");

        BRICOMANIA.setText("BRICOMANIA");
        BRICOMANIA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BRICOMANIAMouseClicked(evt);
            }
        });
        BRICOMANIA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BRICOMANIAActionPerformed(evt);
            }
        });

        MORDIDA.setText("HABITOS DE MORDIDA");
        MORDIDA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MORDIDAMouseClicked(evt);
            }
        });
        MORDIDA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MORDIDAActionPerformed(evt);
            }
        });

        CONTRACCIONES.setText("CONTRACCIONES MUSCULARES");
        CONTRACCIONES.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CONTRACCIONESMouseClicked(evt);
            }
        });
        CONTRACCIONES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CONTRACCIONESActionPerformed(evt);
            }
        });

        BUCAL.setText("RESPIRACION BUCAL");
        BUCAL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BUCALMouseClicked(evt);
            }
        });
        BUCAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUCALActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MORDIDA)
                            .addComponent(BRICOMANIA))
                        .addGap(107, 107, 107)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CONTRACCIONES)
                            .addComponent(BUCAL)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(jLabel12)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BRICOMANIA)
                    .addComponent(CONTRACCIONES))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MORDIDA)
                    .addComponent(BUCAL))
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 420, 430, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Cancelar");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 480, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Expedientes");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 50, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Nuevo Expediente");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Crear Expediente");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/boton 1.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/boton presionado.png"))); // NOI18N
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/boton seleccionado.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 162, 37));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/boton 1.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/boton presionado.png"))); // NOI18N
        jButton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/boton seleccionado.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 162, 37));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/boton 1.png"))); // NOI18N
        jButton3.setBorder(null);
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/boton presionado.png"))); // NOI18N
        jButton3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/boton seleccionado.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, 162, 37));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 102, 255));
        jLabel8.setText("Descripcion");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, -1, -1));

        jScrollPane1.setViewportView(jTextPane1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 550, 380, 110));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 102, 255));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo.jpg"))); // NOI18N
        jLabel13.setText("Nombre:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void ESMALTEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ESMALTEMouseClicked
        esmalte="Esmalte";
    }//GEN-LAST:event_ESMALTEMouseClicked

    private void DENTINAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DENTINAMouseClicked
        dentina=", Dentina";
    }//GEN-LAST:event_DENTINAMouseClicked

    private void RAIZMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RAIZMouseClicked
        raiz=", Raiz";
    }//GEN-LAST:event_RAIZMouseClicked

    private void HUESOSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HUESOSMouseClicked
        huesos=", Huesos";
    }//GEN-LAST:event_HUESOSMouseClicked

    private void HUESOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HUESOSActionPerformed
        huesos=", Huesos";
    }//GEN-LAST:event_HUESOSActionPerformed

    private void ENCIAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ENCIAMouseClicked
        encia=", Encia";
    }//GEN-LAST:event_ENCIAMouseClicked

    private void VELOMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VELOMouseClicked
        velo=", Velo";
    }//GEN-LAST:event_VELOMouseClicked

    private void INSERCIONMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_INSERCIONMouseClicked
        insercion=", Insercion";
    }//GEN-LAST:event_INSERCIONMouseClicked

    private void CARRILLOSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CARRILLOSMouseClicked
        carrillos=", Carrillos";
    }//GEN-LAST:event_CARRILLOSMouseClicked

    private void DESMAYOSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DESMAYOSMouseClicked
        desmayos=", Desmayos";
    }//GEN-LAST:event_DESMAYOSMouseClicked

    private void EMBARAZADAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EMBARAZADAMouseClicked
        embarazada=", Embarazada";
    }//GEN-LAST:event_EMBARAZADAMouseClicked

    private void ONOCLUSIONMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ONOCLUSIONMouseClicked
        onoclusion=", Onoclusion";
    }//GEN-LAST:event_ONOCLUSIONMouseClicked

    private void MAREOSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MAREOSMouseClicked
        mareos=", Mareos";
    }//GEN-LAST:event_MAREOSMouseClicked

    private void MAREOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MAREOSActionPerformed
    mareos=", Mareos";
    }//GEN-LAST:event_MAREOSActionPerformed

    private void OTROSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OTROSMouseClicked
        otros=", Otros";
    }//GEN-LAST:event_OTROSMouseClicked

    private void SOBREMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SOBREMouseClicked
       sobre=", Sobre mordida vertical";
    }//GEN-LAST:event_SOBREMouseClicked

    private void DESGASTEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DESGASTEMouseClicked
        desgaste=", Desgaste"; 
    }//GEN-LAST:event_DESGASTEMouseClicked

    private void INTERMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_INTERMouseClicked
        intercuspideo= ", Intercuspideo";
    }//GEN-LAST:event_INTERMouseClicked

    private void VERTIGOSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VERTIGOSMouseClicked
        vertigos=", Vertigos";
    }//GEN-LAST:event_VERTIGOSMouseClicked

    private void BRICOMANIAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BRICOMANIAMouseClicked
       bricomania=", Bricomania";
    }//GEN-LAST:event_BRICOMANIAMouseClicked

    private void MORDIDAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MORDIDAMouseClicked
        mordida=", Habitos de Mordida";
    }//GEN-LAST:event_MORDIDAMouseClicked

    private void CONTRACCIONESMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CONTRACCIONESMouseClicked
        contraccion=", Contracciones musculares";
    }//GEN-LAST:event_CONTRACCIONESMouseClicked

    private void BUCALMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BUCALMouseClicked
        bucal=", Respiracion bucal";
    }//GEN-LAST:event_BUCALMouseClicked

    private void ESMALTEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ESMALTEActionPerformed
        esmalte="Esmalte";
    }//GEN-LAST:event_ESMALTEActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        boolean bandera = false;
          String sintomas=esmalte+dentina+raiz+huesos+encia+velo+carrillos+insercion+sobre+desgaste+intercuspideo+desmayos+vertigos+
        embarazada+onoclusion+mareos+otros+bricomania+contraccion+mordida+bucal;
     
           String cos="Insert Into expedientes(nombre_paciente, domicilio, telefono,ocupacion,edad,sexo,sintomas,descripcion) values(?,?,?,?,?,?,?,?)";
        String nombre= jTextField1.getText();
        String domicilio = jTextField2.getText();
        String telefono = jTextField3.getText();
        String ocupacion = jTextField4.getText();
        String edadCantidad = jTextField5.getText();
        int edadNumero = Integer.parseInt(jTextField5.getText());
        int opcionCB = jComboBox1.getSelectedIndex();
        
        String jtxt1 =jTextField1.getText();
        jtxt1.replaceAll(" ", "");
        
        String jtxt2 =jTextField2.getText();
        jtxt2.replaceAll(" ", "");
        
        String jtxt3 =jTextField3.getText();
        jtxt3.replaceAll(" ", "");
        
        String jtxt4 =jTextField4.getText();
        jtxt4.replaceAll(" ", "");
        
        String jtxt5 =jTextField5.getText();
        jtxt5.replaceAll(" ", "");
        
        try{
           PreparedStatement pst=con.prepareStatement(cos);
           if(jtxt1.length()==0){
                JOptionPane.showMessageDialog(null,"No introdujo un nombre","Error al insertar",JOptionPane.WARNING_MESSAGE);
                jTextField1.requestFocus();
                bandera = true;
            }else{
                pst.setString(1, jTextField1.getText());
            }
           //pst.setString(1, jTextField1.getText());
           if(jtxt2.length()==0){
               bandera = true;
                JOptionPane.showMessageDialog(null,"No introdujo un Domicilio","Error al insertar",JOptionPane.WARNING_MESSAGE);
                jTextField2.requestFocus();
            }else{
                pst.setString(2, jTextField2.getText());
            }
           //pst.setString(2, jTextField2.getText());
           if(jtxt3.length()==0 || jtxt3.length()<10){
                bandera = true;
                JOptionPane.showMessageDialog(null,"No introdujo un telefono o el telefono esta incompleto","Error al insertar",JOptionPane.WARNING_MESSAGE);
                jTextField3.requestFocus();
            }else{
                pst.setString(3, jTextField3.getText());
            }
           //pst.setString(3, jTextField3.getText());
           if(jtxt4.length()==0){
                bandera = true;
                JOptionPane.showMessageDialog(null,"No introdujo una Ocupacion","Error al insertar",JOptionPane.WARNING_MESSAGE);
                jTextField4.requestFocus();
            }else{
                pst.setString(4, jTextField4.getText());
            }
           //pst.setString(4, jTextField4.getText());
           int num = Integer.parseInt(jTextField5.getText());
           if(jtxt5.length()==0 || num<1){
                bandera = true;
                JOptionPane.showMessageDialog(null,"No introdujo una edad correcta o dejo el campo vacio","Error al insertar",JOptionPane.WARNING_MESSAGE);
                jTextField5.requestFocus();
            }else{
                pst.setString(5, jTextField5.getText());
            }
           //pst.setString(5, jTextField5.getText());
           if(opcionCB==0){
               bandera = true;
                JOptionPane.showMessageDialog(null,"No selecciono un sexo valido","Error al insertar",JOptionPane.WARNING_MESSAGE);
                jComboBox1.requestFocus();
            }else{
                pst.setString(6, jComboBox1.getSelectedItem().toString());
            }
           //pst.setString(6, jComboBox1.getSelectedItem().toString());
           pst.setString(7, sintomas);
           pst.setString(8, jTextPane1.getText());
           
           int resp =-1;
           //int resp = JOptionPane.showConfirmDialog(null, "¿Esta seguro de Crear el expediente?", "Alerta!", JOptionPane.YES_NO_OPTION);
           if(bandera){
               JOptionPane.showMessageDialog(null,"Hubo un error, favor de solucionarlo.");
           }else{
             resp = JOptionPane.showConfirmDialog(null, "¿Esta seguro de Crear el expediente?", "Alerta!", JOptionPane.YES_NO_OPTION);
             switch (resp) {
             case 0:
                 pst.executeUpdate();
                 JOptionPane.showMessageDialog(null, "Registro exitoso");
                 break;
             case 1:
                 break;
             }
           }
           
           /*pst.executeUpdate();
           JOptionPane.showMessageDialog(null, "Registro exitoso");*/
           
      
           }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error en el registro"+e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void RAIZActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RAIZActionPerformed
raiz=", Raiz";
    }//GEN-LAST:event_RAIZActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        IntDocPrincipal abrirventanaDOC = new IntDocPrincipal();
        abrirventanaDOC.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
        jComboBox1.setSelectedIndex(0);
        ESMALTE.setSelected(false);
        DENTINA.setSelected(false);
        RAIZ.setSelected(false);
        HUESOS.setSelected(false);
        ENCIA.setSelected(false);
        VELO.setSelected(false);
        CARRILLOS.setSelected(false);
        INSERCION.setSelected(false);
        SOBRE.setSelected(false);
        DESGASTE.setSelected(false);
        INTER.setSelected(false);
        DESMAYOS.setSelected(false);
        VERTIGOS.setSelected(false);
        EMBARAZADA.setSelected(false);
        ONOCLUSION.setSelected(false);
        MAREOS.setSelected(false);
        OTROS.setSelected(false);
        BRICOMANIA.setSelected(false);
        CONTRACCIONES.setSelected(false);
        MORDIDA.setSelected(false);
        BUCAL.setSelected(false);
        jTextPane1.setText("");
         esmalte="";dentina="";raiz="";huesos="";encia="";velo="";carrillos="";
         insercion="";sobre="";desgaste="";intercuspideo="";desmayos="";vertigos="";
        embarazada="";onoclusion="";
        mareos="";
        otros="";bricomania="";contraccion="";mordida="";bucal="";
        /*dispose();
        Expedientes abrirventanaexpedientes = new Expedientes();
        abrirventanaexpedientes.setVisible(true);*/
        //esmalte=""; dentina="";raiz="";huesos="";encia="";velo=""; carrillos="";insercion="";sobre="";desgaste="";
        //intercuspideo="";desmayos="";vertigos="";
        //embarazada="";onoclusion="";
         //mareos="";otros="";bricomania="";contraccion="";mordida="";bucal="";
    }//GEN-LAST:event_jButton2ActionPerformed

    private void DENTINAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DENTINAActionPerformed
        dentina=", Dentina";
    }//GEN-LAST:event_DENTINAActionPerformed

    private void ENCIAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ENCIAActionPerformed
        encia=", Encia";
    }//GEN-LAST:event_ENCIAActionPerformed

    private void VELOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VELOActionPerformed
        velo=", Velo de paladar";
    }//GEN-LAST:event_VELOActionPerformed

    private void CARRILLOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CARRILLOSActionPerformed
        carrillos=", Carrillos";
    }//GEN-LAST:event_CARRILLOSActionPerformed

    private void INSERCIONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_INSERCIONActionPerformed
        insercion=", Insercion";
    }//GEN-LAST:event_INSERCIONActionPerformed

    private void SOBREActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SOBREActionPerformed
        sobre=", Sobre mordida vertical";
    }//GEN-LAST:event_SOBREActionPerformed

    private void DESGASTEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DESGASTEActionPerformed
        desgaste=", Desgaste";
    }//GEN-LAST:event_DESGASTEActionPerformed

    private void INTERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_INTERActionPerformed
        intercuspideo=", Intercuspideo";
    }//GEN-LAST:event_INTERActionPerformed

    private void DESMAYOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DESMAYOSActionPerformed
       desmayos=", Desmayos";
    }//GEN-LAST:event_DESMAYOSActionPerformed

    private void VERTIGOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VERTIGOSActionPerformed
       vertigos=", Vertigos";
    }//GEN-LAST:event_VERTIGOSActionPerformed

    private void EMBARAZADAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EMBARAZADAActionPerformed
        embarazada=", Se encuentra embarazada";
    }//GEN-LAST:event_EMBARAZADAActionPerformed

    private void ONOCLUSIONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ONOCLUSIONActionPerformed
        onoclusion=", Onoclusion";
    }//GEN-LAST:event_ONOCLUSIONActionPerformed

    private void OTROSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OTROSActionPerformed
        otros=",  Otros";
    }//GEN-LAST:event_OTROSActionPerformed

    private void BRICOMANIAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BRICOMANIAActionPerformed
        bricomania=", Bricomania";
    }//GEN-LAST:event_BRICOMANIAActionPerformed

    private void CONTRACCIONESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CONTRACCIONESActionPerformed
        contraccion=", Contracciones musculares";
    }//GEN-LAST:event_CONTRACCIONESActionPerformed

    private void MORDIDAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MORDIDAActionPerformed
        mordida=", Habitos de mordida";
    }//GEN-LAST:event_MORDIDAActionPerformed

    private void BUCALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUCALActionPerformed
        bucal=", Respiracion bucal";
    }//GEN-LAST:event_BUCALActionPerformed

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
        char c=evt.getKeyChar();
        if(Character.isDigit(c)) {
            getToolkit().beep();
            evt.consume();
        }
        String cad=(""+c).toUpperCase();
        c=cad.charAt(0);
        evt.setKeyChar(c);
    }//GEN-LAST:event_jTextField1KeyTyped

    private void jTextField4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyTyped
        char c=evt.getKeyChar();
        if(Character.isDigit(c)) {
            getToolkit().beep();
            evt.consume();
        }
        String cad=(""+c).toUpperCase();
        c=cad.charAt(0);
        evt.setKeyChar(c);
    }//GEN-LAST:event_jTextField4KeyTyped

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyTyped
        char c=evt.getKeyChar();
        if(Character.isLetter(c)){
            getToolkit().beep();
            evt.consume();
        }
        if (jTextField3.getText().length()== 10){
            evt.consume(); 
        }
    }//GEN-LAST:event_jTextField3KeyTyped

    private void jTextField5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyTyped
        char c=evt.getKeyChar();
        if(Character.isLetter(c)){
            getToolkit().beep();
            evt.consume();
        }
        if (jTextField5.getText().length()== 2){
            evt.consume(); 
        }
    }//GEN-LAST:event_jTextField5KeyTyped

     
        
       
          
        
        
        
        

        
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Expedientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Expedientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Expedientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Expedientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Expedientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton BRICOMANIA;
    private javax.swing.JRadioButton BUCAL;
    private javax.swing.JRadioButton CARRILLOS;
    private javax.swing.JRadioButton CONTRACCIONES;
    private javax.swing.JRadioButton DENTINA;
    private javax.swing.JRadioButton DESGASTE;
    private javax.swing.JRadioButton DESMAYOS;
    private javax.swing.JRadioButton EMBARAZADA;
    private javax.swing.JRadioButton ENCIA;
    private javax.swing.JRadioButton ESMALTE;
    private javax.swing.JRadioButton HUESOS;
    private javax.swing.JRadioButton INSERCION;
    private javax.swing.JRadioButton INTER;
    private javax.swing.JRadioButton MAREOS;
    private javax.swing.JRadioButton MORDIDA;
    private javax.swing.JRadioButton ONOCLUSION;
    private javax.swing.JRadioButton OTROS;
    private javax.swing.JRadioButton RAIZ;
    private javax.swing.JRadioButton SOBRE;
    private javax.swing.JRadioButton VELO;
    private javax.swing.JRadioButton VERTIGOS;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
