/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import javax.swing.table.DefaultTableModel;
import conexionSQL.Conexion;
import java.sql.Connection;
import java.util.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.HashSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author cachi
 */
public class GestionCitas extends javax.swing.JFrame {
        Conexion cc=new Conexion();
        Connection con=cc.conectar();
    /**
     * Creates new form GestionCitas
     */
    public GestionCitas() {
        initComponents();
        this.setResizable(false);
        deshabilitarCampos();
        jButton5.setEnabled(false);
        jButton6.setEnabled(false);
        MostrarCita("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtBNombre = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        txtH = new javax.swing.JTextField();
        txtId = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(736, 449));
        setMinimumSize(new java.awt.Dimension(736, 449));
        setPreferredSize(new java.awt.Dimension(803, 653));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Cancelar");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 560, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Modificar");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 510, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Eliminar");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 510, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Salir");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 510, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Buscar");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Aceptar");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 560, -1, -1));

        jLabel14.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Gestion Citas");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 60, -1, -1));

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "Fecha", "Hora", "Asunto"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tabla);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 346, 370));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 255));
        jLabel1.setText("Nombre:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        txtBNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBNombreActionPerformed(evt);
            }
        });
        txtBNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBNombreKeyTyped(evt);
            }
        });
        getContentPane().add(txtBNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 150, -1));

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/boton 1.png"))); // NOI18N
        btnBuscar.setBorder(null);
        btnBuscar.setBorderPainted(false);
        btnBuscar.setContentAreaFilled(false);
        btnBuscar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/boton presionado.png"))); // NOI18N
        btnBuscar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/boton seleccionado.png"))); // NOI18N
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 70, 20));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 255));
        jLabel2.setText("ID:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 100, -1, -1));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 130, 220, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 255));
        jLabel3.setText("Asunto:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 170, -1, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 170, 220, 210));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 255));
        jLabel4.setText("Fecha:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 400, -1, -1));
        getContentPane().add(jDateChooser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 400, 220, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 255));
        jLabel5.setText("Hora:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 450, -1, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/boton 1.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/boton presionado.png"))); // NOI18N
        jButton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/boton seleccionado.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 500, 162, 37));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/boton 1.png"))); // NOI18N
        jButton3.setBorder(null);
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/boton presionado.png"))); // NOI18N
        jButton3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/boton seleccionado.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 500, 162, 37));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/boton 1.png"))); // NOI18N
        jButton4.setBorder(null);
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/boton presionado.png"))); // NOI18N
        jButton4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/boton seleccionado.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 500, 162, 37));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/boton 1.png"))); // NOI18N
        jButton5.setBorder(null);
        jButton5.setBorderPainted(false);
        jButton5.setContentAreaFilled(false);
        jButton5.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/boton presionado.png"))); // NOI18N
        jButton5.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/boton seleccionado.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 550, 162, 37));

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/boton 1.png"))); // NOI18N
        jButton6.setBorder(null);
        jButton6.setBorderPainted(false);
        jButton6.setContentAreaFilled(false);
        jButton6.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/boton presionado.png"))); // NOI18N
        jButton6.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/boton seleccionado.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 550, 162, 37));
        getContentPane().add(txtH, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 450, 220, -1));
        getContentPane().add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 100, 220, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 255));
        jLabel7.setText("Nombre Paciente:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, -1, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo.jpg"))); // NOI18N
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String txtN =txtBNombre.getText();
        txtN.replaceAll(" ", "");
        
        if(txtN.length()==0){
            JOptionPane.showMessageDialog(null,"No introdujo un nombre por el cual buscar","Error al insertar",JOptionPane.WARNING_MESSAGE);   
        }else{
            MostrarCita(txtBNombre.getText());
            datoNo();
        }
        /*MostrarCita(txtBNombre.getText());
         datoNo();*/
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtBNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBNombreActionPerformed

    private void TablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaMouseClicked
        Visualizar();
    }//GEN-LAST:event_TablaMouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
                    jButton2.setEnabled(true);
                    jButton3.setEnabled(true);
                    jButton4.setEnabled(true);
                    
                    jButton5.setEnabled(false);
                    jButton6.setEnabled(false);
                    deshabilitarCampos();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        habilitarCampos(); 
        jButton2.setEnabled(false);
        jButton3.setEnabled(false);
        jButton4.setEnabled(false);
        
        jButton5.setEnabled(true);
        jButton6.setEnabled(true);
        /*
        int resp=-1;
             resp = JOptionPane.showConfirmDialog(null, "¿Esta seguro de Modificar la Cita?", "Alerta!", JOptionPane.YES_NO_OPTION);
             switch (resp) {
             case 0:
                try {
                    Actualizar();
                    JOptionPane.showMessageDialog(null, "Modificacion exitosa");
                } catch (ParseException ex) {
                    Logger.getLogger(GestionCitas.class.getName()).log(Level.SEVERE, null, ex);
                }
                deshabilitarCampos();
                break;
             case 1:
                 break;
             }
        */
            /*
        try {
                Actualizar();
            } catch (ParseException ex) {
                Logger.getLogger(GestionCitas.class.getName()).log(Level.SEVERE, null, ex);
            }*/
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       int resp=-1;
             resp = JOptionPane.showConfirmDialog(null, "¿Esta seguro de Eliminar la Cita?", "Alerta!", JOptionPane.YES_NO_OPTION);
             switch (resp) {
             case 0:
                Eliminar();
                JOptionPane.showMessageDialog(null, "Se Elimino la cita de forma exitosa");
                limpiarCampos();
                break;
             case 1:
                 break;
             }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtBNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBNombreKeyTyped
        char c=evt.getKeyChar();
        if(Character.isDigit(c)) {
            getToolkit().beep();
            evt.consume();
        }
        String cad=(""+c).toUpperCase();
        c=cad.charAt(0);
        evt.setKeyChar(c);
    }//GEN-LAST:event_txtBNombreKeyTyped

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        int resp=-1;
             resp = JOptionPane.showConfirmDialog(null, "¿Esta seguro de Modificar la Cita?", "Alerta!", JOptionPane.YES_NO_OPTION);
             switch (resp) {
             case 0:
                try {
                    Actualizar();
                    JOptionPane.showMessageDialog(null, "Modificacion exitosa");
                    jButton2.setEnabled(true);
                    jButton3.setEnabled(true);
                    jButton4.setEnabled(true);
                    
                    jButton5.setEnabled(false);
                    jButton6.setEnabled(false);
                    deshabilitarCampos();
                } catch (ParseException ex) {
                    Logger.getLogger(GestionCitas.class.getName()).log(Level.SEVERE, null, ex);
                }
                deshabilitarCampos();
                break;
             case 1:
                 break;
             }
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed
    public void deshabilitarCampos(){
        txtId.setEnabled(false);
        txtId.setEditable(false);
        
        jTextField2.setEnabled(false);
        jTextField2.setEditable(false);
        
        jTextArea1.setEnabled(false);
        jTextArea1.setEditable(false);
        
        jDateChooser2.setEnabled(false);
        jDateChooser2.setFocusable(false);
        
        txtH.setEnabled(false);
        txtH.setEditable(false);
    }
    
    public void habilitarCampos(){
        
        jTextArea1.setEnabled(true);
        jTextArea1.setEditable(true);
        
        jDateChooser2.setEnabled(true);
        jDateChooser2.setFocusable(true);
        
        txtH.setEnabled(true);
        txtH.setEditable(true);
    }
    
    public void Visualizar(){
        int fila=Tabla.getSelectedRow();
        if(fila>=0){
         
            try {
                txtId.setText(Tabla.getValueAt(fila,0).toString());
                jTextField2.setText(Tabla.getValueAt(fila,1).toString());
                jTextArea1.setText(Tabla.getValueAt(fila, 2).toString());
                String fechas= (String) Tabla.getModel().getValueAt(fila, 3);
                SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy");
                jDateChooser2.setDate(df.parse(fechas));
                txtH.setText(Tabla.getValueAt(fila, 4).toString());
            } catch (ParseException ex) {
                Logger.getLogger(GestionCitas.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    
    public void limpiarCampos(){
        txtId.setText(" ");
        jTextField2.setText(" ");
        jTextArea1.setText(" ");
        jDateChooser2.setDate(null);
        txtH.setText(" ");
    }
    
    public void Actualizar() throws ParseException{
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        String fechaComoCadena = sdf.format(jDateChooser2.getDate());
        int bR=JOptionPane.showConfirmDialog(null,"¿Actualizar Registro?","ACTUALIZAR",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        Date dateA = new Date();
        String dateAA = sdf.format(dateA);
        Date fecha1 = sdf.parse(fechaComoCadena);
        Date fecha2 = sdf.parse(dateAA);
        String Hora = txtH.getText();
        if(bR==JOptionPane.YES_NO_OPTION){
            if(fecha1.equals(fecha2)){
                JOptionPane.showMessageDialog(null, "Fecha no valida");

            }
            else if(fecha1.before(fecha2)){
                    JOptionPane.showMessageDialog(null, "Fecha no valida");
            }
            else if(Hora.equals("14:00") || Hora.equals("14:30") || Hora.equals("15:00") || Hora.equals("15:30")){
                JOptionPane.showMessageDialog(null,"Horario fuera de servicio escoja otra hora por favor");
                txtH.requestFocus();
            }
            else{
                try{
                        Statement st = con.createStatement();
                        ResultSet rs = st.executeQuery("SELECT fecha_cita,hora_cita FROM CITAS WHERE fecha_cita LIKE'"+
                                fechaComoCadena+"' AND hora_cita LIKE '"+ Hora +"'");
                        if(rs.next()){
                            getToolkit().beep();
                            JOptionPane.showMessageDialog(null,"Ya otra cita se encuentra registrada en esa fecha");
                            jDateChooser2.requestFocus();
                        }else{
                                PreparedStatement act;
                                act = con.prepareStatement("Update Citas set nombre_paciente='"
                                        +jTextField2.getText()+"',asunto='"+jTextArea1.getText()+"',fecha_cita='"+fechaComoCadena+"',hora_cita='"
                                        +txtH.getText()+"'where id_Cita='"+txtId.getText()+"'");
                                act.executeUpdate();
                                limpiarCampos();
                                MostrarCita("");
                        }
                }
                catch (SQLException ex) {
                        Logger.getLogger(GestionCitas.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
         }
    }
    
    public void Eliminar(){
        int f=Tabla.getSelectedColumn();
        String idCita=Tabla.getValueAt(f,0).toString();
        int bR=JOptionPane.showConfirmDialog(null,"¿Eliminar Registro?","ELIMINAR",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
         if(bR==JOptionPane.YES_NO_OPTION){
            try {
                PreparedStatement borrar=con.prepareStatement("Delete from Citas where id_Cita='"+idCita+"'");
                borrar.executeUpdate();
                MostrarCita("");
                limpiarCampos();
            } catch (SQLException ex) {
                Logger.getLogger(GestionCitas.class.getName()).log(Level.SEVERE, null, ex);
            }
         }
    }
    
    public void datoNo(){
        int r=0;
        String Nombre=txtBNombre.getText();
        try{
          Statement st = con.createStatement();
          ResultSet rs = st.executeQuery("SELECT nombre_paciente FROM CITAS WHERE nombre_paciente LIKE'"+Nombre+"'");  
          if(rs.next()){
               MostrarCita(Nombre);
          }else{
              r=1;
              if(r==1){
                 if(Nombre.equals("")){
                    JOptionPane.showMessageDialog(null,"Ingrese un nombre");
                    MostrarCita(txtBNombre.getText());
                 }else{
                    JOptionPane.showMessageDialog(null,"Nombre no encontrado");
                    txtBNombre.setText("");
                    MostrarCita(txtBNombre.getText());
                 }
              }
          }
        }catch (SQLException ex) {
                Logger.getLogger(GestionCitas.class.getName()).log(Level.SEVERE, null, ex);
         }  
    }
    
    
    public void MostrarCita(String Nombre){
        DefaultTableModel tabla=new DefaultTableModel();
        tabla.addColumn("ID");
        tabla.addColumn("Nombre");
        tabla.addColumn("Asunto");
        tabla.addColumn("Fecha");
        tabla.addColumn("Hora");
        Tabla.setModel(tabla);
        String cons=" ";
        if(Nombre.equals("")){
            cons="Select * from Citas";
        }else{
            cons="Select * from Citas where nombre_paciente like'"+Nombre+"'";
        }
   
        
        String datos[] = new String[5];
        Statement st;
            try {
                
                st = con.createStatement();
                ResultSet rs = st.executeQuery(cons);
                while(rs.next()){
                    datos[0]=rs.getString(1);
                    datos[1]=rs.getString(2);
                    datos[2]=rs.getString(3);
                    datos[3]=rs.getString(4);
                    datos[4]=rs.getString(5);
                    tabla.addRow(datos);
                }
                Tabla.setModel(tabla);
            } catch (SQLException ex) {
                Logger.getLogger(GestionCitas.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionCitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionCitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionCitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionCitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionCitas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabla;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField txtBNombre;
    private javax.swing.JTextField txtH;
    private javax.swing.JTextField txtId;
    // End of variables declaration//GEN-END:variables
}
