/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import javax.swing.table.DefaultTableModel;
import conexionSQL.Conexion;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author cachi
 */
public class ModificarExpedientes extends javax.swing.JFrame {
String esmalte="",dentina="",raiz="",huesos="",encia="",velo="",carrillos="",insercion="",sobre="",desgaste="",intercuspideo="",desmayos="",vertigos="",
        embarazada="",onoclusion="";
String mareos="",otros="",bricomania="",contraccion="",mordida="",bucal="";
    /**
     * Creates new form Expedientes
     */
    public ModificarExpedientes() {
        initComponents();
        this.setResizable(false);
        MostrarExpedientes("");
        jTextField1.setEnabled(false);
        jTextField1.setEditable(false);
    }
    

      Conexion cc=new Conexion();
        Connection con=cc.conectar();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        ESMALTE = new javax.swing.JRadioButton();
        DENTINA = new javax.swing.JRadioButton();
        RAIZ = new javax.swing.JRadioButton();
        HUESOS = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        ENCIA = new javax.swing.JRadioButton();
        VELO = new javax.swing.JRadioButton();
        INSERCION = new javax.swing.JRadioButton();
        CARRILLOS = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        DESMAYOS = new javax.swing.JRadioButton();
        EMBARAZADA = new javax.swing.JRadioButton();
        ONOCLUSION = new javax.swing.JRadioButton();
        MAREOS = new javax.swing.JRadioButton();
        OTROS = new javax.swing.JRadioButton();
        SOBRE = new javax.swing.JRadioButton();
        DESGASTE = new javax.swing.JRadioButton();
        INTER = new javax.swing.JRadioButton();
        VERTIGOS = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        BRICOMANIA = new javax.swing.JRadioButton();
        MORDIDA = new javax.swing.JRadioButton();
        CONTRACCIONES = new javax.swing.JRadioButton();
        BUCAL = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        txtBNombre = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextPane3 = new javax.swing.JTextPane();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(734, 444));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nombre:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, -1, -1));

        jLabel2.setText("Domicilio:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, -1, -1));

        jLabel3.setText("Telefono:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, -1, -1));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, 200, -1));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, 200, -1));

        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField3KeyTyped(evt);
            }
        });
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, 200, -1));

        jLabel4.setText("Ocupacion:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, -1, -1));
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 210, 200, -1));

        jLabel5.setText("Edad:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, -1, -1));

        jTextField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField5KeyTyped(evt);
            }
        });
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 240, 60, -1));

        jLabel6.setText("Sexo:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 240, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Masculino", "Femenino" }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 240, 80, -1));

        jLabel7.setText("Sintomas");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 0, -1, -1));

        jLabel9.setText("EXAMEN DE TEJIDOS");

        ESMALTE.setText("ESMALTE");
        ESMALTE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ESMALTEMouseClicked(evt);
            }
        });
        ESMALTE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ESMALTEActionPerformed(evt);
            }
        });

        DENTINA.setText("DENTINA");
        DENTINA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DENTINAMouseClicked(evt);
            }
        });
        DENTINA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DENTINAActionPerformed(evt);
            }
        });

        RAIZ.setText("RAIZ");
        RAIZ.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RAIZMouseClicked(evt);
            }
        });
        RAIZ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RAIZActionPerformed(evt);
            }
        });

        HUESOS.setText("HUESOS");
        HUESOS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HUESOSMouseClicked(evt);
            }
        });
        HUESOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HUESOSActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(RAIZ)
                                .addGap(28, 28, 28))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addComponent(ESMALTE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(HUESOS)
                            .addComponent(DENTINA))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ESMALTE)
                    .addComponent(DENTINA))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RAIZ)
                    .addComponent(HUESOS))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 20, -1, -1));

        jLabel10.setText("BLANDOS");

        ENCIA.setText("ENCIA");
        ENCIA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ENCIAMouseClicked(evt);
            }
        });
        ENCIA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ENCIAActionPerformed(evt);
            }
        });

        VELO.setText("VELO DE PALADAR");
        VELO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VELOMouseClicked(evt);
            }
        });
        VELO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VELOActionPerformed(evt);
            }
        });

        INSERCION.setText("INSERCION");
        INSERCION.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                INSERCIONMouseClicked(evt);
            }
        });
        INSERCION.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                INSERCIONActionPerformed(evt);
            }
        });

        CARRILLOS.setText("CARRILLOS");
        CARRILLOS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CARRILLOSMouseClicked(evt);
            }
        });
        CARRILLOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CARRILLOSActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(ENCIA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(VELO)
                        .addGap(113, 113, 113))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(CARRILLOS)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(INSERCION)
                        .addGap(155, 155, 155))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ENCIA)
                    .addComponent(VELO))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CARRILLOS)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(INSERCION)
                        .addContainerGap())))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 30, 210, -1));

        jLabel11.setText("OCLUSION");

        DESMAYOS.setText("DESMAYOS");
        DESMAYOS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DESMAYOSMouseClicked(evt);
            }
        });
        DESMAYOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DESMAYOSActionPerformed(evt);
            }
        });

        EMBARAZADA.setText("SE ENCUENTRA EMBARAZADA");
        EMBARAZADA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EMBARAZADAMouseClicked(evt);
            }
        });
        EMBARAZADA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EMBARAZADAActionPerformed(evt);
            }
        });

        ONOCLUSION.setText("ONOCLUSION");
        ONOCLUSION.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ONOCLUSIONMouseClicked(evt);
            }
        });
        ONOCLUSION.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ONOCLUSIONActionPerformed(evt);
            }
        });

        MAREOS.setText("MAREOS");
        MAREOS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MAREOSMouseClicked(evt);
            }
        });
        MAREOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MAREOSActionPerformed(evt);
            }
        });

        OTROS.setText("OTROS");
        OTROS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OTROSMouseClicked(evt);
            }
        });
        OTROS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OTROSActionPerformed(evt);
            }
        });

        SOBRE.setText("SOBRE MORDIDA VERTICAL");
        SOBRE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SOBREMouseClicked(evt);
            }
        });
        SOBRE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SOBREActionPerformed(evt);
            }
        });

        DESGASTE.setText("DESGASTE ");
        DESGASTE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DESGASTEMouseClicked(evt);
            }
        });
        DESGASTE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DESGASTEActionPerformed(evt);
            }
        });

        INTER.setText("INTERCUSPIDEO");
        INTER.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                INTERMouseClicked(evt);
            }
        });
        INTER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                INTERActionPerformed(evt);
            }
        });

        VERTIGOS.setText("VERTIGOS");
        VERTIGOS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VERTIGOSMouseClicked(evt);
            }
        });
        VERTIGOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VERTIGOSActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(213, 213, 213))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ONOCLUSION)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(MAREOS)
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(SOBRE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(DESMAYOS)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DESGASTE)
                            .addComponent(VERTIGOS))))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(INTER)
                    .addComponent(EMBARAZADA)
                    .addComponent(OTROS))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SOBRE)
                    .addComponent(DESGASTE)
                    .addComponent(INTER))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VERTIGOS)
                    .addComponent(DESMAYOS)
                    .addComponent(EMBARAZADA))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ONOCLUSION)
                    .addComponent(MAREOS)
                    .addComponent(OTROS)))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 140, -1, -1));

        jLabel12.setText("HABITOS");

        BRICOMANIA.setText("BRICOMANIA");
        BRICOMANIA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BRICOMANIAMouseClicked(evt);
            }
        });
        BRICOMANIA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BRICOMANIAActionPerformed(evt);
            }
        });

        MORDIDA.setText("HABITOS DE MORDIDA");
        MORDIDA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MORDIDAMouseClicked(evt);
            }
        });
        MORDIDA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MORDIDAActionPerformed(evt);
            }
        });

        CONTRACCIONES.setText("CONTRACCIONES MUSCULARES");
        CONTRACCIONES.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CONTRACCIONESMouseClicked(evt);
            }
        });
        CONTRACCIONES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CONTRACCIONESActionPerformed(evt);
            }
        });

        BUCAL.setText("RESPIRACION BUCAL");
        BUCAL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BUCALMouseClicked(evt);
            }
        });
        BUCAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUCALActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MORDIDA)
                            .addComponent(BRICOMANIA))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CONTRACCIONES)
                            .addComponent(BUCAL)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(jLabel12)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BRICOMANIA)
                    .addComponent(CONTRACCIONES))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MORDIDA)
                    .addComponent(BUCAL))
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 280, -1, -1));

        jButton1.setText("Modificar Expediente");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 280, 210, -1));

        jButton2.setText("Historial");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 0, 100, -1));

        jButton3.setText("Cancelar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 360, 210, -1));

        jLabel8.setText("Descripcion");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 380, -1, -1));

        jScrollPane1.setViewportView(jTextPane1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 400, 380, 120));

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "Domicilio", "Telefono", "Ocupacion"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tabla.setToolTipText("");
        Tabla.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Tabla);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 330, 370));

        jLabel13.setText("Buscar por Nombre:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, -1, -1));

        txtBNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBNombreActionPerformed(evt);
            }
        });
        txtBNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBNombreKeyTyped(evt);
            }
        });
        getContentPane().add(txtBNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 160, -1));

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, -1, -1));

        jTextPane2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTextPane2.setEnabled(false);
        jScrollPane3.setViewportView(jTextPane2);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 170, 80));

        jTextPane3.setEnabled(false);
        jScrollPane4.setViewportView(jTextPane3);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 500, 190, 80));

        jLabel15.setText("Sintomas");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, -1, -1));

        jLabel16.setText("Descripcion");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 480, -1, -1));

        txtId.setEnabled(false);
        getContentPane().add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, 90, -1));

        jLabel14.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 51, 51));
        jLabel14.setText("ID");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, 100, -1));

        jButton4.setText("Nueva Modificacion");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 320, 210, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void ESMALTEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ESMALTEMouseClicked
        esmalte="Esmalte";
    }//GEN-LAST:event_ESMALTEMouseClicked

    private void DENTINAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DENTINAMouseClicked
        dentina=", Dentina";
    }//GEN-LAST:event_DENTINAMouseClicked

    private void RAIZMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RAIZMouseClicked
        raiz=", Raiz";
    }//GEN-LAST:event_RAIZMouseClicked

    private void HUESOSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HUESOSMouseClicked
        huesos=", Huesos";
    }//GEN-LAST:event_HUESOSMouseClicked

    private void HUESOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HUESOSActionPerformed
        huesos=", Huesos";
    }//GEN-LAST:event_HUESOSActionPerformed

    private void ENCIAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ENCIAMouseClicked
        encia=", Encia";
    }//GEN-LAST:event_ENCIAMouseClicked

    private void VELOMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VELOMouseClicked
        velo=", Velo";
    }//GEN-LAST:event_VELOMouseClicked

    private void INSERCIONMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_INSERCIONMouseClicked
        insercion=", Insercion";
    }//GEN-LAST:event_INSERCIONMouseClicked

    private void CARRILLOSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CARRILLOSMouseClicked
        carrillos=", Carrillos";
    }//GEN-LAST:event_CARRILLOSMouseClicked

    private void DESMAYOSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DESMAYOSMouseClicked
        desmayos=", Desmayos";
    }//GEN-LAST:event_DESMAYOSMouseClicked

    private void EMBARAZADAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EMBARAZADAMouseClicked
        embarazada=", Embarazada";
    }//GEN-LAST:event_EMBARAZADAMouseClicked

    private void ONOCLUSIONMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ONOCLUSIONMouseClicked
        onoclusion=", Onoclusion";
    }//GEN-LAST:event_ONOCLUSIONMouseClicked

    private void MAREOSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MAREOSMouseClicked
        mareos=", Mareos";
    }//GEN-LAST:event_MAREOSMouseClicked

    private void MAREOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MAREOSActionPerformed
    mareos=", Mareos";
    }//GEN-LAST:event_MAREOSActionPerformed

    private void OTROSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OTROSMouseClicked
        otros=", Otros";
    }//GEN-LAST:event_OTROSMouseClicked

    private void SOBREMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SOBREMouseClicked
       sobre=", Sobre mordida vertical";
    }//GEN-LAST:event_SOBREMouseClicked

    private void DESGASTEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DESGASTEMouseClicked
        desgaste=", Desgaste"; 
    }//GEN-LAST:event_DESGASTEMouseClicked

    private void INTERMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_INTERMouseClicked
        
    }//GEN-LAST:event_INTERMouseClicked

    private void VERTIGOSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VERTIGOSMouseClicked
        vertigos=", Vertigos";
    }//GEN-LAST:event_VERTIGOSMouseClicked

    private void BRICOMANIAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BRICOMANIAMouseClicked
       bricomania=", Bricomania";
    }//GEN-LAST:event_BRICOMANIAMouseClicked

    private void MORDIDAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MORDIDAMouseClicked
        mordida=", Habitos de Mordida";
    }//GEN-LAST:event_MORDIDAMouseClicked

    private void CONTRACCIONESMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CONTRACCIONESMouseClicked
        contraccion=", Contracciones musculares";
    }//GEN-LAST:event_CONTRACCIONESMouseClicked

    private void BUCALMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BUCALMouseClicked
        bucal=", Respiracion bucal";
    }//GEN-LAST:event_BUCALMouseClicked

    private void ESMALTEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ESMALTEActionPerformed
        esmalte="Esmalte";
    }//GEN-LAST:event_ESMALTEActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
          String sintomas=esmalte+dentina+raiz+huesos+encia+velo+carrillos+insercion+sobre+desgaste+intercuspideo+desmayos+vertigos+
        embarazada+onoclusion+mareos+otros+bricomania+contraccion+mordida+bucal;
      PreparedStatement act;
             
      jTextPane2.setText(sintomas);
      jTextPane3.setText(jTextPane1.getText());
      
        try{
            act = con.prepareStatement("Update expedientes set nombre_paciente='"
                    +jTextField1.getText()+"',domicilio='"+jTextField2.getText()+"',telefono='"+jTextField3.getText()+"',ocupacion='"
                    +jTextField4.getText()+"',edad='"+jTextField5.getText()+"',sexo='"+jComboBox1.getSelectedItem().toString()+"',sintomas='"+sintomas
                    +"',descripcion='"+jTextPane1.getText()+"'where id_expedientes='"+txtId.getText()+"'");
            act.executeUpdate();
            MostrarExpedientes("");
         }
        catch (SQLException ex) {
                Logger.getLogger(GestionCitas.class.getName()).log(Level.SEVERE, null, ex);
        }
      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void RAIZActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RAIZActionPerformed
raiz=", Raiz";
    }//GEN-LAST:event_RAIZActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
        Historial abrirventanaexpedientes = new Historial();
        abrirventanaexpedientes.setVisible(true);
      
    }//GEN-LAST:event_jButton2ActionPerformed

    private void DENTINAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DENTINAActionPerformed
        dentina=", Dentina";
    }//GEN-LAST:event_DENTINAActionPerformed

    private void ENCIAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ENCIAActionPerformed
        encia=", Encia";
    }//GEN-LAST:event_ENCIAActionPerformed

    private void VELOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VELOActionPerformed
        velo=", Velo de paladar";
    }//GEN-LAST:event_VELOActionPerformed

    private void CARRILLOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CARRILLOSActionPerformed
        carrillos=", Carrillos";
    }//GEN-LAST:event_CARRILLOSActionPerformed

    private void INSERCIONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_INSERCIONActionPerformed
        insercion=", Insercion";
    }//GEN-LAST:event_INSERCIONActionPerformed

    private void SOBREActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SOBREActionPerformed
        sobre=", Sobre mordida vertical";
    }//GEN-LAST:event_SOBREActionPerformed

    private void DESGASTEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DESGASTEActionPerformed
        desgaste=", Desgaste";
    }//GEN-LAST:event_DESGASTEActionPerformed

    private void INTERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_INTERActionPerformed
        intercuspideo=", Intercuspideo";
    }//GEN-LAST:event_INTERActionPerformed

    private void DESMAYOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DESMAYOSActionPerformed
       desmayos=", Desmayos";
    }//GEN-LAST:event_DESMAYOSActionPerformed

    private void VERTIGOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VERTIGOSActionPerformed
       vertigos=", Vertigos";
    }//GEN-LAST:event_VERTIGOSActionPerformed

    private void EMBARAZADAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EMBARAZADAActionPerformed
        embarazada=", Se encuentra embarazada";
    }//GEN-LAST:event_EMBARAZADAActionPerformed

    private void ONOCLUSIONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ONOCLUSIONActionPerformed
        onoclusion=", Onoclusion";
    }//GEN-LAST:event_ONOCLUSIONActionPerformed

    private void OTROSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OTROSActionPerformed
        otros=",  Otros";
    }//GEN-LAST:event_OTROSActionPerformed

    private void BRICOMANIAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BRICOMANIAActionPerformed
        bricomania=", Bricomania";
    }//GEN-LAST:event_BRICOMANIAActionPerformed

    private void CONTRACCIONESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CONTRACCIONESActionPerformed
        contraccion=", Contracciones musculares";
    }//GEN-LAST:event_CONTRACCIONESActionPerformed

    private void MORDIDAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MORDIDAActionPerformed
        mordida=", Habitos de mordida";
    }//GEN-LAST:event_MORDIDAActionPerformed

    private void BUCALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUCALActionPerformed
        bucal=", Respiracion bucal";
    }//GEN-LAST:event_BUCALActionPerformed

    private void TablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaMouseClicked
        visualizar();
    }//GEN-LAST:event_TablaMouseClicked

    private void txtBNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBNombreActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        MostrarExpedientes(txtBNombre.getText());
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        txtId.setText("");
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
        jComboBox1.setSelectedIndex(0);
        ESMALTE.setSelected(false);
        DENTINA.setSelected(false);
        RAIZ.setSelected(false);
        HUESOS.setSelected(false);
        ENCIA.setSelected(false);
        VELO.setSelected(false);
        CARRILLOS.setSelected(false);
        INSERCION.setSelected(false);
        SOBRE.setSelected(false);
        DESGASTE.setSelected(false);
        INTER.setSelected(false);
        DESMAYOS.setSelected(false);
        VERTIGOS.setSelected(false);
        EMBARAZADA.setSelected(false);
        ONOCLUSION.setSelected(false);
        MAREOS.setSelected(false);
        OTROS.setSelected(false);
        BRICOMANIA.setSelected(false);
        CONTRACCIONES.setSelected(false);
        MORDIDA.setSelected(false);
        BUCAL.setSelected(false);
        jTextPane1.setText("");
         esmalte="";dentina="";raiz="";huesos="";encia="";velo="";carrillos="";
         insercion="";sobre="";desgaste="";intercuspideo="";desmayos="";vertigos="";
        embarazada="";onoclusion="";
        mareos="";
        otros="";bricomania="";contraccion="";mordida="";bucal="";
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyTyped
        char c=evt.getKeyChar();
        if(Character.isLetter(c)){
            getToolkit().beep();
            evt.consume();
        }
        if (jTextField3.getText().length()== 10){
            evt.consume(); 
        }
    }//GEN-LAST:event_jTextField3KeyTyped

    private void jTextField5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyTyped
        char c=evt.getKeyChar();
        if(Character.isLetter(c)){
            getToolkit().beep();
            evt.consume();
        }
        if (jTextField5.getText().length()== 2){
            evt.consume(); 
        }
    }//GEN-LAST:event_jTextField5KeyTyped

    private void txtBNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBNombreKeyTyped
       char c=evt.getKeyChar();
        if(Character.isDigit(c)) {
            getToolkit().beep();
            evt.consume();
        }
        String cad=(""+c).toUpperCase();
        c=cad.charAt(0);
        evt.setKeyChar(c);
    }//GEN-LAST:event_txtBNombreKeyTyped

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
        char c=evt.getKeyChar();
        if(Character.isDigit(c)) {
            getToolkit().beep();
            evt.consume();
        }
        String cad=(""+c).toUpperCase();
        c=cad.charAt(0);
        evt.setKeyChar(c);
    }//GEN-LAST:event_jTextField1KeyTyped

       
      public void visualizar(){
    int fila=Tabla.getSelectedRow();
    if(fila>=0){

         txtId.setText(Tabla.getValueAt(fila, 0).toString());
        jTextField1.setText(Tabla.getValueAt(fila, 1).toString());
        jTextField2.setText(Tabla.getValueAt(fila,2).toString());
        jTextField3.setText(Tabla.getValueAt(fila, 3).toString());
        jTextField4.setText(Tabla.getValueAt(fila, 4).toString());
        jTextField5.setText(Tabla.getValueAt(fila, 5).toString());
        jTextPane2.setText(Tabla.getValueAt(fila, 6).toString());
        jTextPane3.setText(Tabla.getValueAt(fila, 7).toString());
        
        
  
    }//if
    }//visualizar
    
   
    
    
          public void MostrarExpedientes(String Nombre){
    DefaultTableModel tabla= new DefaultTableModel();
    tabla.addColumn("ID");
     tabla.addColumn("Nombre");
     tabla.addColumn("Domicilio");
     tabla.addColumn("Telefono");
     tabla.addColumn("Ocupacion");
     tabla.addColumn("Edad");
     tabla.addColumn("Sintomas");
     tabla.addColumn("Descripcion");

    Tabla.setModel(tabla);
    String cons=" ";
    if(Nombre.equals("")){
    cons="select id_expedientes,nombre_paciente,domicilio,telefono,ocupacion,edad,sintomas,descripcion from expedientes";
    }else{
        cons="Select id_expedientes,nombre_paciente,domicilio,telefono,ocupacion,edad,sintomas,descripcion from expedientes where nombre_paciente like'%"+Nombre+"%'";
    }
    
    
    
    String datos [] = new String[8];
    Statement st;
    try{
        st = con.createStatement();
        ResultSet rs= st.executeQuery(cons);
        while(rs.next()){
             datos[0]=rs.getString(1);
                    datos[1]=rs.getString(2);
                    datos[2]=rs.getString(3);
                    datos[3]=rs.getString(4);
                    datos[4]=rs.getString(5);
                    datos[5]=rs.getString(6);
                    datos[6]=rs.getString(7);
                    datos[7]=rs.getString(8);
                    tabla.addRow(datos);
        }
         Tabla.setModel(tabla);
    }catch (SQLException ex) {
                Logger.getLogger(GestionCitas.class.getName()).log(Level.SEVERE, null, ex);
            }
          }
       
          
        
        
         
  
        
    
      

        
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarExpedientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarExpedientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarExpedientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarExpedientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificarExpedientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton BRICOMANIA;
    private javax.swing.JRadioButton BUCAL;
    private javax.swing.JRadioButton CARRILLOS;
    private javax.swing.JRadioButton CONTRACCIONES;
    private javax.swing.JRadioButton DENTINA;
    private javax.swing.JRadioButton DESGASTE;
    private javax.swing.JRadioButton DESMAYOS;
    private javax.swing.JRadioButton EMBARAZADA;
    private javax.swing.JRadioButton ENCIA;
    private javax.swing.JRadioButton ESMALTE;
    private javax.swing.JRadioButton HUESOS;
    private javax.swing.JRadioButton INSERCION;
    private javax.swing.JRadioButton INTER;
    private javax.swing.JRadioButton MAREOS;
    private javax.swing.JRadioButton MORDIDA;
    private javax.swing.JRadioButton ONOCLUSION;
    private javax.swing.JRadioButton OTROS;
    private javax.swing.JRadioButton RAIZ;
    private javax.swing.JRadioButton SOBRE;
    private javax.swing.JTable Tabla;
    private javax.swing.JRadioButton VELO;
    private javax.swing.JRadioButton VERTIGOS;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPane2;
    private javax.swing.JTextPane jTextPane3;
    private javax.swing.JTextField txtBNombre;
    private javax.swing.JTextField txtId;
    // End of variables declaration//GEN-END:variables
}
