/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import conexionSQL.Conexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author lalos
 */
public class nCotra extends javax.swing.JFrame {
        Conexion cc=new Conexion();
        Connection con=cc.conectar();
    /**
     * Creates new form nCotra
     */
    public nCotra() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(697, 497));
        setMinimumSize(new java.awt.Dimension(697, 497));
        setPreferredSize(new java.awt.Dimension(697, 497));
        getContentPane().setLayout(null);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Confirmar");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(160, 350, 91, 22);

        jLabel1.setText("Nueva Contraseña");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 190, 90, 14);

        jLabel2.setText("Confirmar Contraseña");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 220, 106, 14);
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(140, 190, 106, 20);
        getContentPane().add(jPasswordField2);
        jPasswordField2.setBounds(140, 220, 106, 20);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/boton 1.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(130, 340, 162, 40);

        jLabel3.setText("Usuario");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(80, 150, 36, 14);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DOCTORA", "ASISTENTE" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(140, 150, 190, 20);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo Contraseña.jpg"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 700, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        actualizarPass();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(nCotra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(nCotra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(nCotra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(nCotra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new nCotra().setVisible(true);
            }
        });
    }

    public void actualizarPass(){
        String nuevaC=jPasswordField1.getText();
        String confirmarC=jPasswordField2.getText();
        String TipoU=(String)jComboBox1.getSelectedItem();
         int bR=JOptionPane.showConfirmDialog(null,"¿ACTUALIZAR CONTRASEÑA?","CONTRASEÑA",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
         if(bR==JOptionPane.YES_NO_OPTION){
        if(nuevaC.equals(confirmarC)){
            try{
                PreparedStatement act;
                act = con.prepareStatement("Update USUARIO set NuevoUsuario = 0 where NUSUARIO ='"+TipoU+"'");
                act.executeUpdate();
                act = con.prepareStatement("Update USUARIO set PASS ='"+nuevaC+"' where NUSUARIO ='"+TipoU+"'");
                act.executeUpdate();
                JOptionPane.showMessageDialog(null,"Contraseña actualizada");
                dispose();
            }catch (SQLException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            JOptionPane.showMessageDialog(null,"La constraseñas no son iguales");
            jPasswordField1.setText("");
            jPasswordField2.setText("");
        }   
       }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    // End of variables declaration//GEN-END:variables
}
